version: '3'
services:
    metabeemRelayChat:                       # Service Name
        container_name: metabeem-relay-chat
        hostname: metabeem-relay-chat
        build:
            context: .
        image: metabeem-relay-chat:latest
        ports:
            # 指定端口映射，类似 docker run 的 -p 选项，注意使用字符串形式
            # [local port]:[container port]
            - "6616:6616"
        #volumes:
            #- ./deploy/etc/localtime:/etc/localtime:ro
            #- ./deploy/etc/timezone:/etc/timezone:ro
            #- ./deploy/etc/hosts:/etc/hosts:ro
        #environment:
        #    - HTTP_PORT=6612
        #    - STORE_DATABASE_URL=mongodb://host.docker.internal:27017/metabeem
